package product

type Product struct {
	ID_                      string        `json:"_id"`
	Complete                 int           `json:"complete"`
	CategoriesPropertiesTags []string      `json:"categories_properties_tags"`
	BrandsHierarchy          []string      `json:"brands_hierarchy"`
	Lc                       string        `json:"lc"`
	EnvironmentalScoreTags   []string      `json:"environmental_score_tags"`
	NutriscoreVersion        string        `json:"nutriscore_version"`
	LanguagesTags            []string      `json:"languages_tags"`
	Code                     string        `json:"code"`
	ServingQuantity          float64       `json:"serving_quantity"`
	ProductNameDe            string        `json:"product_name_de"`
	ID                       string        `json:"id"`
	AllergensHierarchy       []interface{} `json:"allergens_hierarchy"`
	NutritionGradesTags      []string      `json:"nutrition_grades_tags"`
	TracesFromIngredients    string        `json:"traces_from_ingredients"`
	Traces                   string        `json:"traces"`
	BrandsOld                string        `json:"brands_old"`
	NutritionDataPer         string        `json:"nutrition_data_per"`
	NutritionDataPreparedPer string        `json:"nutrition_data_prepared_per"`
	Nutriscore2023Tags       []string      `json:"nutriscore_2023_tags"`
	ServingSize              string        `json:"serving_size"`
	NutritionScoreBeverage   int           `json:"nutrition_score_beverage"`
	Lang                     string        `json:"lang"`
	CountriesTags            []string      `json:"countries_tags"`
	AllergensFromIngredients string        `json:"allergens_from_ingredients"`
	CreatedT                 int           `json:"created_t"`
	NutritionGradeFr         string        `json:"nutrition_grade_fr"`
	NutritionGrades          string        `json:"nutrition_grades"`
	NutritionData            string        `json:"nutrition_data"`
	DataQualityTags          []string      `json:"data_quality_tags"`
	Countries                string        `json:"countries"`
	MiscTags                 []string      `json:"misc_tags"`
	CodesTags                []string      `json:"codes_tags"`
	UniqueScansN             int           `json:"unique_scans_n"`
	FoodGroupsTags           []interface{} `json:"food_groups_tags"`
	States                   string        `json:"states"`
	ProductQuantity          float64       `json:"product_quantity"`
	Brands                   string        `json:"brands"`
	Quantity                 string        `json:"quantity"`
	EnvironmentalScoreData   struct {
		Status  string `json:"status"`
		Missing struct {
			Categories  int `json:"categories"`
			Labels      int `json:"labels"`
			Ingredients int `json:"ingredients"`
			Packagings  int `json:"packagings"`
			Origins     int `json:"origins"`
		} `json:"missing"`
		MissingAgribalyseMatchWarning int `json:"missing_agribalyse_match_warning"`
		Agribalyse                    struct {
			Warning string `json:"warning"`
		} `json:"agribalyse"`
		MissingKeyData int `json:"missing_key_data"`
		Adjustments    struct {
			OriginsOfIngredients struct {
				EpiValue int `json:"epi_value"`
				Values   struct {
					Lb    int `json:"lb"`
					Es    int `json:"es"`
					Fr    int `json:"fr"`
					Lu    int `json:"lu"`
					De    int `json:"de"`
					Nl    int `json:"nl"`
					Is    int `json:"is"`
					Al    int `json:"al"`
					Xk    int `json:"xk"`
					Ro    int `json:"ro"`
					Ch    int `json:"ch"`
					Dz    int `json:"dz"`
					Ps    int `json:"ps"`
					Mc    int `json:"mc"`
					Ax    int `json:"ax"`
					Md    int `json:"md"`
					Hr    int `json:"hr"`
					Fi    int `json:"fi"`
					Dk    int `json:"dk"`
					Tr    int `json:"tr"`
					Cz    int `json:"cz"`
					Cy    int `json:"cy"`
					No    int `json:"no"`
					At    int `json:"at"`
					Fo    int `json:"fo"`
					Us    int `json:"us"`
					Tn    int `json:"tn"`
					Lv    int `json:"lv"`
					Je    int `json:"je"`
					Ly    int `json:"ly"`
					Bg    int `json:"bg"`
					Sk    int `json:"sk"`
					World int `json:"world"`
					Sm    int `json:"sm"`
					Gg    int `json:"gg"`
					Me    int `json:"me"`
					It    int `json:"it"`
					Be    int `json:"be"`
					Rs    int `json:"rs"`
					Si    int `json:"si"`
					Im    int `json:"im"`
					Pl    int `json:"pl"`
					Gr    int `json:"gr"`
					Pt    int `json:"pt"`
					Lt    int `json:"lt"`
					Mk    int `json:"mk"`
					Sj    int `json:"sj"`
					Hu    int `json:"hu"`
					Li    int `json:"li"`
					Se    int `json:"se"`
					Uk    int `json:"uk"`
					Il    int `json:"il"`
					Sy    int `json:"sy"`
					Ma    int `json:"ma"`
					Ie    int `json:"ie"`
					Mt    int `json:"mt"`
					Ba    int `json:"ba"`
					Eg    int `json:"eg"`
					Va    int `json:"va"`
					Gi    int `json:"gi"`
					Ua    int `json:"ua"`
					Ee    int `json:"ee"`
					Ad    int `json:"ad"`
				} `json:"values"`
				TransportationValues struct {
					Cy    int `json:"cy"`
					Tr    int `json:"tr"`
					Cz    int `json:"cz"`
					Dk    int `json:"dk"`
					At    int `json:"at"`
					No    int `json:"no"`
					Mc    int `json:"mc"`
					Ps    int `json:"ps"`
					Fi    int `json:"fi"`
					Hr    int `json:"hr"`
					Md    int `json:"md"`
					Ax    int `json:"ax"`
					Us    int `json:"us"`
					Fo    int `json:"fo"`
					Tn    int `json:"tn"`
					Nl    int `json:"nl"`
					Is    int `json:"is"`
					Es    int `json:"es"`
					Lb    int `json:"lb"`
					Fr    int `json:"fr"`
					De    int `json:"de"`
					Lu    int `json:"lu"`
					Dz    int `json:"dz"`
					Ch    int `json:"ch"`
					Xk    int `json:"xk"`
					Al    int `json:"al"`
					Ro    int `json:"ro"`
					Se    int `json:"se"`
					Uk    int `json:"uk"`
					Mk    int `json:"mk"`
					Sj    int `json:"sj"`
					Hu    int `json:"hu"`
					Pt    int `json:"pt"`
					Lt    int `json:"lt"`
					Li    int `json:"li"`
					Ee    int `json:"ee"`
					Ua    int `json:"ua"`
					Gi    int `json:"gi"`
					Va    int `json:"va"`
					Ad    int `json:"ad"`
					Sy    int `json:"sy"`
					Il    int `json:"il"`
					Ba    int `json:"ba"`
					Eg    int `json:"eg"`
					Mt    int `json:"mt"`
					Ie    int `json:"ie"`
					Ma    int `json:"ma"`
					Gg    int `json:"gg"`
					World int `json:"world"`
					Sm    int `json:"sm"`
					Be    int `json:"be"`
					Rs    int `json:"rs"`
					It    int `json:"it"`
					Me    int `json:"me"`
					Bg    int `json:"bg"`
					Ly    int `json:"ly"`
					Je    int `json:"je"`
					Lv    int `json:"lv"`
					Sk    int `json:"sk"`
					Gr    int `json:"gr"`
					Pl    int `json:"pl"`
					Im    int `json:"im"`
					Si    int `json:"si"`
				} `json:"transportation_values"`
				AggregatedOrigins []struct {
					Percent int    `json:"percent"`
					Origin  string `json:"origin"`
				} `json:"aggregated_origins"`
				OriginsFromOriginsField []string `json:"origins_from_origins_field"`
				TransportationScores    struct {
					Ch    float64 `json:"ch"`
					Dz    float64 `json:"dz"`
					Ro    float64 `json:"ro"`
					Xk    float64 `json:"xk"`
					Al    float64 `json:"al"`
					Is    float64 `json:"is"`
					Nl    float64 `json:"nl"`
					De    float64 `json:"de"`
					Lu    float64 `json:"lu"`
					Fr    float64 `json:"fr"`
					Lb    float64 `json:"lb"`
					Es    float64 `json:"es"`
					Tn    float64 `json:"tn"`
					Us    float64 `json:"us"`
					Fo    float64 `json:"fo"`
					At    float64 `json:"at"`
					No    float64 `json:"no"`
					Cy    float64 `json:"cy"`
					Dk    float64 `json:"dk"`
					Tr    float64 `json:"tr"`
					Cz    float64 `json:"cz"`
					Hr    float64 `json:"hr"`
					Fi    float64 `json:"fi"`
					Ax    float64 `json:"ax"`
					Md    float64 `json:"md"`
					Ps    float64 `json:"ps"`
					Mc    float64 `json:"mc"`
					Pl    float64 `json:"pl"`
					Gr    float64 `json:"gr"`
					Si    float64 `json:"si"`
					Im    float64 `json:"im"`
					Rs    float64 `json:"rs"`
					Be    float64 `json:"be"`
					Me    float64 `json:"me"`
					It    float64 `json:"it"`
					Sm    float64 `json:"sm"`
					World float64 `json:"world"`
					Gg    float64 `json:"gg"`
					Sk    float64 `json:"sk"`
					Lv    float64 `json:"lv"`
					Je    float64 `json:"je"`
					Ly    float64 `json:"ly"`
					Bg    float64 `json:"bg"`
					Ad    float64 `json:"ad"`
					Ee    float64 `json:"ee"`
					Va    float64 `json:"va"`
					Gi    float64 `json:"gi"`
					Ua    float64 `json:"ua"`
					Eg    float64 `json:"eg"`
					Ba    float64 `json:"ba"`
					Ie    float64 `json:"ie"`
					Ma    float64 `json:"ma"`
					Mt    float64 `json:"mt"`
					Il    float64 `json:"il"`
					Sy    float64 `json:"sy"`
					Uk    float64 `json:"uk"`
					Se    float64 `json:"se"`
					Li    float64 `json:"li"`
					Sj    float64 `json:"sj"`
					Mk    float64 `json:"mk"`
					Hu    float64 `json:"hu"`
					Pt    float64 `json:"pt"`
					Lt    float64 `json:"lt"`
				} `json:"transportation_scores"`
				Warning               string   `json:"warning"`
				EpiScore              int      `json:"epi_score"`
				OriginsFromCategories []string `json:"origins_from_categories"`
			} `json:"origins_of_ingredients"`
			ThreatenedSpecies struct {
				Warning string `json:"warning"`
			} `json:"threatened_species"`
			ProductionSystem struct {
				Labels  []interface{} `json:"labels"`
				Value   int           `json:"value"`
				Warning string        `json:"warning"`
			} `json:"production_system"`
			Packaging struct {
				Warning string `json:"warning"`
				Value   int    `json:"value"`
			} `json:"packaging"`
		} `json:"adjustments"`
		Grade string `json:"grade"`
	} `json:"environmental_score_data"`
	UnknownNutrientsTags []interface{} `json:"unknown_nutrients_tags"`
	ScansN               int           `json:"scans_n"`
	WeighersTags         []interface{} `json:"weighers_tags"`
	CategoriesProperties struct {
	} `json:"categories_properties"`
	BrandsLc            string        `json:"brands_lc"`
	ProductType         string        `json:"product_type"`
	NoNutritionData     string        `json:"no_nutrition_data"`
	Packagings          []interface{} `json:"packagings"`
	PackagingsMaterials struct {
	} `json:"packagings_materials"`
	DataSourcesTags    []string      `json:"data_sources_tags"`
	NutriscoreGrade    string        `json:"nutriscore_grade"`
	NovaGroupsTags     []string      `json:"nova_groups_tags"`
	AllergensFromUser  string        `json:"allergens_from_user"`
	LastModifiedT      int           `json:"last_modified_t"`
	CountriesHierarchy []string      `json:"countries_hierarchy"`
	TracesTags         []interface{} `json:"traces_tags"`
	Rev                int           `json:"rev"`
	Nutriments         struct {
		Energy100G              int     `json:"energy_100g"`
		Fat                     int     `json:"fat"`
		EnergyKcal              int     `json:"energy-kcal"`
		SugarsValue             float64 `json:"sugars_value"`
		SugarsUnit              string  `json:"sugars_unit"`
		Carbohydrates           float64 `json:"carbohydrates"`
		Carbohydrates100G       float64 `json:"carbohydrates_100g"`
		Energy                  int     `json:"energy"`
		SugarsServing           float64 `json:"sugars_serving"`
		Fat100G                 int     `json:"fat_100g"`
		ProteinsValue           int     `json:"proteins_value"`
		EnergyKcalUnit          string  `json:"energy-kcal_unit"`
		CarbohydratesValue      float64 `json:"carbohydrates_value"`
		Sugars100G              float64 `json:"sugars_100g"`
		FatUnit                 string  `json:"fat_unit"`
		CarbohydratesServing    float64 `json:"carbohydrates_serving"`
		Proteins                int     `json:"proteins"`
		EnergyValue             int     `json:"energy_value"`
		EnergyUnit              string  `json:"energy_unit"`
		ProteinsUnit            string  `json:"proteins_unit"`
		EnergyKcalValue         int     `json:"energy-kcal_value"`
		EnergyKcal100G          int     `json:"energy-kcal_100g"`
		EnergyKcalServing       float64 `json:"energy-kcal_serving"`
		FatServing              int     `json:"fat_serving"`
		CarbohydratesUnit       string  `json:"carbohydrates_unit"`
		FatValue                int     `json:"fat_value"`
		Proteins100G            int     `json:"proteins_100g"`
		ProteinsServing         int     `json:"proteins_serving"`
		EnergyKcalValueComputed int     `json:"energy-kcal_value_computed"`
		EnergyServing           int     `json:"energy_serving"`
		Sugars                  float64 `json:"sugars"`
	} `json:"nutriments"`
	ServingQuantityUnit string   `json:"serving_quantity_unit"`
	CountriesLc         string   `json:"countries_lc"`
	NovaGroupDebug      string   `json:"nova_group_debug"`
	NutriscoreTags      []string `json:"nutriscore_tags"`
	Nutriscore          struct {
		Num2021 struct {
			Data struct {
				Sugars                                   float64     `json:"sugars"`
				Energy                                   int         `json:"energy"`
				IsBeverage                               int         `json:"is_beverage"`
				IsWater                                  int         `json:"is_water"`
				Sodium                                   interface{} `json:"sodium"`
				IsCheese                                 int         `json:"is_cheese"`
				IsFat                                    int         `json:"is_fat"`
				Proteins                                 int         `json:"proteins"`
				SaturatedFat                             int         `json:"saturated_fat"`
				Fiber                                    int         `json:"fiber"`
				SaturatedFatRatio                        int         `json:"saturated_fat_ratio"`
				FruitsVegetablesNutsColzaWalnutOliveOils int         `json:"fruits_vegetables_nuts_colza_walnut_olive_oils"`
			} `json:"data"`
			Grade                string `json:"grade"`
			NutriscoreComputed   int    `json:"nutriscore_computed"`
			NutriscoreApplicable int    `json:"nutriscore_applicable"`
			NutrientsAvailable   int    `json:"nutrients_available"`
			CategoryAvailable    int    `json:"category_available"`
		} `json:"2021"`
		Num2023 struct {
			NutriscoreComputed int    `json:"nutriscore_computed"`
			Grade              string `json:"grade"`
			Data               struct {
				Proteins                int         `json:"proteins"`
				IsFatOilNutsSeeds       int         `json:"is_fat_oil_nuts_seeds"`
				SaturatedFat            int         `json:"saturated_fat"`
				Fiber                   interface{} `json:"fiber"`
				FruitsVegetablesLegumes interface{} `json:"fruits_vegetables_legumes"`
				SaturatedFatRatio       int         `json:"saturated_fat_ratio"`
				Salt                    interface{} `json:"salt"`
				Sugars                  float64     `json:"sugars"`
				IsRedMeatProduct        int         `json:"is_red_meat_product"`
				IsBeverage              int         `json:"is_beverage"`
				Energy                  int         `json:"energy"`
				IsWater                 int         `json:"is_water"`
				IsCheese                int         `json:"is_cheese"`
			} `json:"data"`
			CategoryAvailable    int `json:"category_available"`
			NutrientsAvailable   int `json:"nutrients_available"`
			NutriscoreApplicable int `json:"nutriscore_applicable"`
		} `json:"2023"`
	} `json:"nutriscore"`
	Completeness                                float64       `json:"completeness"`
	ProductName                                 string        `json:"product_name"`
	PackagingMaterialsTags                      []interface{} `json:"packaging_materials_tags"`
	Keywords                                    []string      `json:"_keywords"`
	LastUpdatedT                                int           `json:"last_updated_t"`
	EntryDatesTags                              []string      `json:"entry_dates_tags"`
	LanguagesHierarchy                          []string      `json:"languages_hierarchy"`
	MainCountriesTags                           []interface{} `json:"main_countries_tags"`
	DataQualityInfoTags                         []string      `json:"data_quality_info_tags"`
	Nutriscore2021Tags                          []string      `json:"nutriscore_2021_tags"`
	MaxImgid                                    string        `json:"max_imgid"`
	StatesTags                                  []string      `json:"states_tags"`
	NutritionScoreWarningNoFruitsVegetablesNuts int           `json:"nutrition_score_warning_no_fruits_vegetables_nuts"`
	EnvironmentalScoreGrade                     string        `json:"environmental_score_grade"`
	PopularityTags                              []string      `json:"popularity_tags"`
	PackagingRecyclingTags                      []interface{} `json:"packaging_recycling_tags"`
	CheckersTags                                []interface{} `json:"checkers_tags"`
	NutrientLevels                              struct {
	} `json:"nutrient_levels"`
	PnnsGroups1Tags              []string      `json:"pnns_groups_1_tags"`
	LastEditDatesTags            []string      `json:"last_edit_dates_tags"`
	NutritionScoreWarningNoFiber int           `json:"nutrition_score_warning_no_fiber"`
	InformersTags                []string      `json:"informers_tags"`
	PnnsGroups2                  string        `json:"pnns_groups_2"`
	BrandsTags                   []string      `json:"brands_tags"`
	Allergens                    string        `json:"allergens"`
	PnnsGroups1                  string        `json:"pnns_groups_1"`
	EcoscoreTags                 []string      `json:"ecoscore_tags"`
	PnnsGroups2Tags              []string      `json:"pnns_groups_2_tags"`
	PopularityKey                int           `json:"popularity_key"`
	AllergensTags                []interface{} `json:"allergens_tags"`
}
