package product

type Product struct {
	ID_         string `json:"_id" bson:"_id"`
	Brands      string `json:"brands" bson:"brands"`
	ProductName string `json:"product_name" bson:"product_name"`
	Quantity    string `json:"quantity" bson:"quantity"`
	Nutriments  struct {
		Energy100g                   float64 `json:"energy_100g" bson:"energy_100g"`
		Energy                       float64 `json:"energy" bson:"energy"`
		EnergyKj100g                 float64 `json:"energy-kj_100g" bson:"energy-kj_100g"`
		EnergyKj                     float64 `json:"energy-kj" bson:"energy-kj"`
		EnergyKcal100g               float64 `json:"energy-kcal_100g" bson:"energy-kcal_100g"`
		EnergyKcal                   float64 `json:"energy-kcal" bson:"energy-kcal"`
		Proteins100g                 float64 `json:"proteins_100g" bson:"proteins_100g"`
		Proteins                     float64 `json:"proteins" bson:"proteins"`
		Casein100g                   float64 `json:"casein_100g" bson:"casein_100g"`
		Casein                       float64 `json:"casein" bson:"casein"`
		SerumProteins100g            float64 `json:"serum-proteins_100g" bson:"serum-proteins_100g"`
		SerumProteins                float64 `json:"serum-proteins" bson:"serum-proteins"`
		Nucleotides100g              float64 `json:"nucleotides_100g" bson:"nucleotides_100g"`
		Nucleotides                  float64 `json:"nucleotides" bson:"nucleotides"`
		Carbohydrates100g            float64 `json:"carbohydrates_100g" bson:"carbohydrates_100g"`
		Carbohydrates                float64 `json:"carbohydrates" bson:"carbohydrates"`
		Sugars100g                   float64 `json:"sugars_100g" bson:"sugars_100g"`
		Sugars                       float64 `json:"sugars" bson:"sugars"`
		Sucrose100g                  float64 `json:"sucrose_100g" bson:"sucrose_100g"`
		Sucrose                      float64 `json:"sucrose" bson:"sucrose"`
		Glucose100g                  float64 `json:"glucose_100g" bson:"glucose_100g"`
		Glucose                      float64 `json:"glucose" bson:"glucose"`
		Fructose100g                 float64 `json:"fructose_100g" bson:"fructose_100g"`
		Fructose                     float64 `json:"fructose" bson:"fructose"`
		Lactose100g                  float64 `json:"lactose_100g" bson:"lactose_100g"`
		Lactose                      float64 `json:"lactose" bson:"lactose"`
		Maltose100g                  float64 `json:"maltose_100g" bson:"maltose_100g"`
		Maltose                      float64 `json:"maltose" bson:"maltose"`
		Maltodextrins100g            float64 `json:"maltodextrins_100g" bson:"maltodextrins_100g"`
		Maltodextrins                float64 `json:"maltodextrins" bson:"maltodextrins"`
		Starch100g                   float64 `json:"starch_100g" bson:"starch_100g"`
		Starch                       float64 `json:"starch" bson:"starch"`
		Polyols100g                  float64 `json:"polyols_100g" bson:"polyols_100g"`
		Polyols                      float64 `json:"polyols" bson:"polyols"`
		Fat100g                      float64 `json:"fat_100g" bson:"fat_100g"`
		Fat                          float64 `json:"fat" bson:"fat"`
		SaturatedFat100g             float64 `json:"saturated-fat_100g" bson:"saturated-fat_100g"`
		SaturatedFat                 float64 `json:"saturated-fat" bson:"saturated-fat"`
		ButyricAcid100g              float64 `json:"butyric-acid_100g" bson:"butyric-acid_100g"`
		ButyricAcid                  float64 `json:"butyric-acid" bson:"butyric-acid"`
		CaproicAcid100g              float64 `json:"caproic-acid_100g" bson:"caproic-acid_100g"`
		CaproicAcid                  float64 `json:"caproic-acid" bson:"caproic-acid"`
		CaprylicAcid100g             float64 `json:"caprylic-acid_100g" bson:"caprylic-acid_100g"`
		CaprylicAcid                 float64 `json:"caprylic-acid" bson:"caprylic-acid"`
		CapricAcid100g               float64 `json:"capric-acid_100g" bson:"capric-acid_100g"`
		CapricAcid                   float64 `json:"capric-acid" bson:"capric-acid"`
		LauricAcid100g               float64 `json:"lauric-acid_100g" bson:"lauric-acid_100g"`
		LauricAcid                   float64 `json:"lauric-acid" bson:"lauric-acid"`
		MyristicAcid100g             float64 `json:"myristic-acid_100g" bson:"myristic-acid_100g"`
		MyristicAcid                 float64 `json:"myristic-acid" bson:"myristic-acid"`
		PalmiticAcid100g             float64 `json:"palmitic-acid_100g" bson:"palmitic-acid_100g"`
		PalmiticAcid                 float64 `json:"palmitic-acid" bson:"palmitic-acid"`
		StearicAcid100g              float64 `json:"stearic-acid_100g" bson:"stearic-acid_100g"`
		StearicAcid                  float64 `json:"stearic-acid" bson:"stearic-acid"`
		ArachidicAcid100g            float64 `json:"arachidic-acid_100g" bson:"arachidic-acid_100g"`
		ArachidicAcid                float64 `json:"arachidic-acid" bson:"arachidonic-acid"`
		BehenicAcid100g              float64 `json:"behenic-acid_100g" bson:"behenic-acid_100g"`
		BehenicAcid                  float64 `json:"behenic-acid" bson:"behenic-acid"`
		LignocericAcid100g           float64 `json:"lignoceric-acid_100g" bson:"lignoceric-acid_100g"`
		LignocericAcid               float64 `json:"lignoceric-acid" bson:"lignoceric-acid"`
		CeroticAcid100g              float64 `json:"cerotic-acid_100g" bson:"cerotic-acid_100g"`
		CeroticAcid                  float64 `json:"cerotic-acid" bson:"cerotic-acid"`
		MontanicAcid100g             float64 `json:"montanic-acid_100g" bson:"montanic-acid_100g"`
		MontanicAcid                 float64 `json:"montanic-acid" bson:"montanic-acid"`
		MelissicAcid100g             float64 `json:"melissic-acid_100g" bson:"melissic-acid_100g"`
		MelissicAcid                 float64 `json:"melissic-acid" bson:"melissic-acid"`
		MonounsaturatedFat100g       float64 `json:"monounsaturated-fat_100g" bson:"monounsaturated-fat_100g"`
		MonounsaturatedFat           float64 `json:"monounsaturated-fat" bson:"monounsaturated-fat"`
		PolyunsaturatedFat100g       float64 `json:"polyunsaturated-fat_100g" bson:"polyunsaturated-fat_100g"`
		PolyunsaturatedFat           float64 `json:"polyunsaturated-fat" bson:"polyunsaturated-fat"`
		Omega3Fat100g                float64 `json:"omega-3-fat_100g" bson:"omega-3-fat_100g"`
		Omega3Fat                    float64 `json:"omega-3-fat" bson:"omega-3-fat"`
		AlphaLinolenicAcid100g       float64 `json:"alpha-linolenic-acid_100g" bson:"alpha-linolenic-acid_100g"`
		AlphaLinolenicAcid           float64 `json:"alpha-linolenic-acid" bson:"alpha-linolenic-acid"`
		EicosapentaenoicAcid100g     float64 `json:"eicosapentaenoic-acid_100g" bson:"eicosapentaenoic-acid_100g"`
		EicosapentaenoicAcid         float64 `json:"eicosapentaenoic-acid" bson:"eicosapentaenoic-acid"`
		DocosahexaenoicAcid100g      float64 `json:"docosahexaenoic-acid_100g" bson:"docosahexaenoic-acid_100g"`
		DocosahexaenoicAcid          float64 `json:"docosahexaenoic-acid" bson:"docosahexaenoic-acid"`
		Omega6Fat100g                float64 `json:"omega-6-fat_100g" bson:"omega-6-fat_100g"`
		Omega6Fat                    float64 `json:"omega-6-fat" bson:"omega-6-fat"`
		LinoleicAcid100g             float64 `json:"linoleic-acid_100g" bson:"linoleic-acid_100g"`
		LinoleicAcid                 float64 `json:"linoleic-acid" bson:"linoleic-acid"`
		GammaLinolenicAcid100g       float64 `json:"gamma-linolenic-acid_100g" bson:"gamma-linolenic-acid_100g"`
		GammaLinolenicAcid           float64 `json:"gamma-linolenic-acid" bson:"gamma-linolenic-acid"`
		DihomoGammaLinolenicAcid100g float64 `json:"dihomo-gamma-linolenic-acid_100g" bson:"dihomo-gamma-linolenic-acid_100g"`
		DihomoGammaLinolenicAcid     float64 `json:"dihomo-gamma-linolenic-acid" bson:"dihomo-gamma-linolenic-acid"`
		Omega9Fat100g                float64 `json:"omega-9-fat_100g" bson:"omega-9-fat_100g"`
		Omega9Fat                    float64 `json:"omega-9-fat" bson:"omega-9-fat"`
		OleicAcid100g                float64 `json:"oleic-acid_100g" bson:"oleic-acid_100g"`
		OleicAcid                    float64 `json:"oleic-acid" bson:"oleic-acid"`
		ElaidicAcid100g              float64 `json:"elaidic-acid_100g" bson:"elaidic-acid_100g"`
		ElaidicAcid                  float64 `json:"elaidic-acid" bson:"elaidic-acid"`
		GondoicAcid100g              float64 `json:"gondoic-acid_100g" bson:"gondoic-acid_100g"`
		GondoicAcid                  float64 `json:"gondoic-acid" bson:"gondoic-acid"`
		MeadAcid100g                 float64 `json:"mead-acid_100g" bson:"mead-acid_100g"`
		MeadAcid                     float64 `json:"mead-acid" bson:"mead-acid"`
		ErucicAcid100g               float64 `json:"erucic-acid_100g" bson:"erucic-acid_100g"`
		ErucicAcid                   float64 `json:"erucic-acid" bson:"erucic-acid"`
		NervonicAcid100g             float64 `json:"nervonic-acid_100g" bson:"nervonic-acid_100g"`
		NervonicAcid                 float64 `json:"nervonic-acid" bson:"nervonic-acid"`
		TransFat100g                 float64 `json:"trans-fat_100g" bson:"trans-fat_100g"`
		TransFat                     float64 `json:"trans-fat" bson:"trans-fat"`
		Cholesterol100g              float64 `json:"cholesterol_100g" bson:"cholesterol_100g"`
		Cholesterol                  float64 `json:"cholesterol" bson:"cholesterol"`
		Fiber100g                    float64 `json:"fiber_100g" bson:"fiber_100g"`
		Fiber                        float64 `json:"fiber" bson:"fiber"`
		Sodium100g                   float64 `json:"sodium_100g" bson:"sodium_100g"`
		Sodium                       float64 `json:"sodium" bson:"sodium"`
		Alcohol100g                  float64 `json:"alcohol_100g" bson:"alcohol_100g"`
		Alcohol                      float64 `json:"alcohol" bson:"alcohol"`
		VitaminA100g                 float64 `json:"vitamin-a_100g" bson:"vitamin-a_100g"`
		VitaminA                     float64 `json:"vitamin-a" bson:"vitamin-a"`
		VitaminD100g                 float64 `json:"vitamin-d_100g" bson:"vitamin-d_100g"`
		VitaminD                     float64 `json:"vitamin-d" bson:"vitamin-d"`
		VitaminE100g                 float64 `json:"vitamin-e_100g" bson:"vitamin-e_100g"`
		VitaminE                     float64 `json:"vitamin-e" bson:"vitamin-e"`
		VitaminK100g                 float64 `json:"vitamin-k_100g" bson:"vitamin-k_100g"`
		VitaminK                     float64 `json:"vitamin-k" bson:"vitamin-k"`
		VitaminC100g                 float64 `json:"vitamin-c_100g" bson:"vitamin-c_100g"`
		VitaminC                     float64 `json:"vitamin-c" bson:"vitamin-c"`
		VitaminB1100g                float64 `json:"vitamin-b1_100g" bson:"vitamin-b1_100g"`
		VitaminB1                    float64 `json:"vitamin-b1" bson:"vitamin-b1"`
		VitaminB2100g                float64 `json:"vitamin-b2_100g" bson:"vitamin-b2_100g"`
		VitaminB2                    float64 `json:"vitamin-b2" bson:"vitamin-b2"`
		VitaminPp100g                float64 `json:"vitamin-pp_100g" bson:"vitamin-pp_100g"`
		VitaminPp                    float64 `json:"vitamin-pp" bson:"vitamin-pp"`
		VitaminB6100g                float64 `json:"vitamin-b6_100g" bson:"vitamin-b6_100g"`
		VitaminB6                    float64 `json:"vitamin-b6" bson:"vitamin-b6"`
		VitaminB9100g                float64 `json:"vitamin-b9_100g" bson:"vitamin-b9_100g"`
		VitaminB9                    float64 `json:"vitamin-b9" bson:"vitamin-b9"`
		VitaminB12100g               float64 `json:"vitamin-b12_100g" bson:"vitamin-b12_100g"`
		VitaminB12                   float64 `json:"vitamin-b12" bson:"vitamin-b12"`
		Biotin100g                   float64 `json:"biotin_100g" bson:"biotin_100g"`
		Biotin                       float64 `json:"biotin" bson:"biotin"`
		PantothenicAcid100g          float64 `json:"pantothenic-acid_100g" bson:"pantothenic-acid_100g"`
		PantothenicAcid              float64 `json:"pantothenic-acid" bson:"pantothenic-acid"`
		Silica100g                   float64 `json:"silica_100g" bson:"silica_100g"`
		Silica                       float64 `json:"silica" bson:"silica"`
		Bicarbonate100g              float64 `json:"bicarbonate_100g" bson:"bicarbonate_100g"`
		Bicarbonate                  float64 `json:"bicarbonate" bson:"bicarbonate"`
		Potassium100g                float64 `json:"potassium_100g" bson:"potassium_100g"`
		Potassium                    float64 `json:"potassium" bson:"potassium"`
		Chloride100g                 float64 `json:"chloride_100g" bson:"chloride_100g"`
		Chloride                     float64 `json:"chloride" bson:"chloride"`
		Calcium100g                  float64 `json:"calcium_100g" bson:"calcium_100g"`
		Calcium                      float64 `json:"calcium" bson:"calcium"`
		Phosphorus100g               float64 `json:"phosphorus_100g" bson:"phosphorus_100g"`
		Phosphorus                   float64 `json:"phosphorus" bson:"phosphorus"`
		Iron100g                     float64 `json:"iron_100g" bson:"iron_100g"`
		Iron                         float64 `json:"iron" bson:"iron"`
		Magnesium100g                float64 `json:"magnesium_100g" bson:"magnesium_100g"`
		Magnesium                    float64 `json:"magnesium" bson:"magnesium"`
		Zinc100g                     float64 `json:"zinc_100g" bson:"zinc_100g"`
		Zinc                         float64 `json:"zinc" bson:"zinc"`
		Copper100g                   float64 `json:"copper_100g" bson:"copper_100g"`
		Copper                       float64 `json:"copper" bson:"copper"`
		Manganese100g                float64 `json:"manganese_100g" bson:"manganese_100g"`
		Manganese                    float64 `json:"manganese" bson:"manganese"`
		Fluoride100g                 float64 `json:"fluoride_100g" bson:"fluoride_100g"`
		Fluoride                     float64 `json:"fluoride" bson:"fluoride"`
		Selenium100g                 float64 `json:"selenium_100g" bson:"selenium_100g"`
		Selenium                     float64 `json:"selenium" bson:"selenium"`
		Chromium100g                 float64 `json:"chromium_100g" bson:"chromium_100g"`
		Chromium                     float64 `json:"chromium" bson:"chromium"`
		Molybdenum100g               float64 `json:"molybdenum_100g" bson:"molybdenum_100g"`
		Molybdenum                   float64 `json:"molybdenum" bson:"molybdenum"`
		Iodine100g                   float64 `json:"iodine_100g" bson:"iodine_100g"`
		Iodine                       float64 `json:"iodine" bson:"iodine"`
		Caffeine100g                 float64 `json:"caffeine_100g" bson:"caffeine_100g"`
		Caffeine                     float64 `json:"caffeine" bson:"caffeine"`
		Taurine100g                  float64 `json:"taurine_100g" bson:"taurine_100g"`
		Taurine                      float64 `json:"taurine" bson:"taurine"`
		Ph100g                       float64 `json:"ph_100g" bson:"ph_100g"`
		Ph                           float64 `json:"ph" bson:"ph"`
		FruitsVegetablesNuts100g     float64 `json:"fruits-vegetables-nuts_100g" bson:"fruits-vegetables-nuts_100g"`
		FruitsVegetablesNuts         float64 `json:"fruits-vegetables-nuts" bson:"fruits-vegetables-nuts"`
		CarbonFootprint100g          float64 `json:"carbon-footprint_100g" bson:"carbon-footprint_100g"`
		CarbonFootprint              float64 `json:"carbon-footprint" bson:"carbon-footprint"`
		NutritionScoreFr100g         float64 `json:"nutrition-score-fr_100g" bson:"nutrition-score-fr_100g"`
		NutritionScoreFr             float64 `json:"nutrition-score-fr" bson:"nutrition-score-fr"`
		NutritionScoreUk100g         float64 `json:"nutrition-score-uk_100g" bson:"nutrition-score-uk_100g"`
		NutritionScoreUk             float64 `json:"nutrition-score-uk" bson:"nutrition-score-uk"`
	}
	NutrimentsEstimated struct {
		Energy100g                   float64 `json:"energy_100g" bson:"energy_100g"`
		Energy                       float64 `json:"energy" bson:"energy"`
		EnergyKj100g                 float64 `json:"energy-kj_100g" bson:"energy-kj_100g"`
		EnergyKj                     float64 `json:"energy-kj" bson:"energy-kj"`
		EnergyKcal100g               float64 `json:"energy-kcal_100g" bson:"energy-kcal_100g"`
		EnergyKcal                   float64 `json:"energy-kcal" bson:"energy-kcal"`
		Proteins100g                 float64 `json:"proteins_100g" bson:"proteins_100g"`
		Proteins                     float64 `json:"proteins" bson:"proteins"`
		Casein100g                   float64 `json:"casein_100g" bson:"casein_100g"`
		Casein                       float64 `json:"casein" bson:"casein"`
		SerumProteins100g            float64 `json:"serum-proteins_100g" bson:"serum-proteins_100g"`
		SerumProteins                float64 `json:"serum-proteins" bson:"serum-proteins"`
		Nucleotides100g              float64 `json:"nucleotides_100g" bson:"nucleotides_100g"`
		Nucleotides                  float64 `json:"nucleotides" bson:"nucleotides"`
		Carbohydrates100g            float64 `json:"carbohydrates_100g" bson:"carbohydrates_100g"`
		Carbohydrates                float64 `json:"carbohydrates" bson:"carbohydrates"`
		Sugars100g                   float64 `json:"sugars_100g" bson:"sugars_100g"`
		Sugars                       float64 `json:"sugars" bson:"sugars"`
		Sucrose100g                  float64 `json:"sucrose_100g" bson:"sucrose_100g"`
		Sucrose                      float64 `json:"sucrose" bson:"sucrose"`
		Glucose100g                  float64 `json:"glucose_100g" bson:"glucose_100g"`
		Glucose                      float64 `json:"glucose" bson:"glucose"`
		Fructose100g                 float64 `json:"fructose_100g" bson:"fructose_100g"`
		Fructose                     float64 `json:"fructose" bson:"fructose"`
		Lactose100g                  float64 `json:"lactose_100g" bson:"lactose_100g"`
		Lactose                      float64 `json:"lactose" bson:"lactose"`
		Maltose100g                  float64 `json:"maltose_100g" bson:"maltose_100g"`
		Maltose                      float64 `json:"maltose" bson:"maltose"`
		Maltodextrins100g            float64 `json:"maltodextrins_100g" bson:"maltodextrins_100g"`
		Maltodextrins                float64 `json:"maltodextrins" bson:"maltodextrins"`
		Starch100g                   float64 `json:"starch_100g" bson:"starch_100g"`
		Starch                       float64 `json:"starch" bson:"starch"`
		Polyols100g                  float64 `json:"polyols_100g" bson:"polyols_100g"`
		Polyols                      float64 `json:"polyols" bson:"polyols"`
		Fat100g                      float64 `json:"fat_100g" bson:"fat_100g"`
		Fat                          float64 `json:"fat" bson:"fat"`
		SaturatedFat100g             float64 `json:"saturated-fat_100g" bson:"saturated-fat_100g"`
		SaturatedFat                 float64 `json:"saturated-fat" bson:"saturated-fat"`
		ButyricAcid100g              float64 `json:"butyric-acid_100g" bson:"butyric-acid_100g"`
		ButyricAcid                  float64 `json:"butyric-acid" bson:"butyric-acid"`
		CaproicAcid100g              float64 `json:"caproic-acid_100g" bson:"caproic-acid_100g"`
		CaproicAcid                  float64 `json:"caproic-acid" bson:"caproic-acid"`
		CaprylicAcid100g             float64 `json:"caprylic-acid_100g" bson:"caprylic-acid_100g"`
		CaprylicAcid                 float64 `json:"caprylic-acid" bson:"caprylic-acid"`
		CapricAcid100g               float64 `json:"capric-acid_100g" bson:"capric-acid_100g"`
		CapricAcid                   float64 `json:"capric-acid" bson:"capric-acid"`
		LauricAcid100g               float64 `json:"lauric-acid_100g" bson:"lauric-acid_100g"`
		LauricAcid                   float64 `json:"lauric-acid" bson:"lauric-acid"`
		MyristicAcid100g             float64 `json:"myristic-acid_100g" bson:"myristic-acid_100g"`
		MyristicAcid                 float64 `json:"myristic-acid" bson:"myristic-acid"`
		PalmiticAcid100g             float64 `json:"palmitic-acid_100g" bson:"palmitic-acid_100g"`
		PalmiticAcid                 float64 `json:"palmitic-acid" bson:"palmitic-acid"`
		StearicAcid100g              float64 `json:"stearic-acid_100g" bson:"stearic-acid_100g"`
		StearicAcid                  float64 `json:"stearic-acid" bson:"stearic-acid"`
		ArachidicAcid100g            float64 `json:"arachidic-acid_100g" bson:"arachidic-acid_100g"`
		ArachidicAcid                float64 `json:"arachidic-acid" bson:"arachidonic-acid"`
		BehenicAcid100g              float64 `json:"behenic-acid_100g" bson:"behenic-acid_100g"`
		BehenicAcid                  float64 `json:"behenic-acid" bson:"behenic-acid"`
		LignocericAcid100g           float64 `json:"lignoceric-acid_100g" bson:"lignoceric-acid_100g"`
		LignocericAcid               float64 `json:"lignoceric-acid" bson:"lignoceric-acid"`
		CeroticAcid100g              float64 `json:"cerotic-acid_100g" bson:"cerotic-acid_100g"`
		CeroticAcid                  float64 `json:"cerotic-acid" bson:"cerotic-acid"`
		MontanicAcid100g             float64 `json:"montanic-acid_100g" bson:"montanic-acid_100g"`
		MontanicAcid                 float64 `json:"montanic-acid" bson:"montanic-acid"`
		MelissicAcid100g             float64 `json:"melissic-acid_100g" bson:"melissic-acid_100g"`
		MelissicAcid                 float64 `json:"melissic-acid" bson:"melissic-acid"`
		MonounsaturatedFat100g       float64 `json:"monounsaturated-fat_100g" bson:"monounsaturated-fat_100g"`
		MonounsaturatedFat           float64 `json:"monounsaturated-fat" bson:"monounsaturated-fat"`
		PolyunsaturatedFat100g       float64 `json:"polyunsaturated-fat_100g" bson:"polyunsaturated-fat_100g"`
		PolyunsaturatedFat           float64 `json:"polyunsaturated-fat" bson:"polyunsaturated-fat"`
		Omega3Fat100g                float64 `json:"omega-3-fat_100g" bson:"omega-3-fat_100g"`
		Omega3Fat                    float64 `json:"omega-3-fat" bson:"omega-3-fat"`
		AlphaLinolenicAcid100g       float64 `json:"alpha-linolenic-acid_100g" bson:"alpha-linolenic-acid_100g"`
		AlphaLinolenicAcid           float64 `json:"alpha-linolenic-acid" bson:"alpha-linolenic-acid"`
		EicosapentaenoicAcid100g     float64 `json:"eicosapentaenoic-acid_100g" bson:"eicosapentaenoic-acid_100g"`
		EicosapentaenoicAcid         float64 `json:"eicosapentaenoic-acid" bson:"eicosapentaenoic-acid"`
		DocosahexaenoicAcid100g      float64 `json:"docosahexaenoic-acid_100g" bson:"docosahexaenoic-acid_100g"`
		DocosahexaenoicAcid          float64 `json:"docosahexaenoic-acid" bson:"docosahexaenoic-acid"`
		Omega6Fat100g                float64 `json:"omega-6-fat_100g" bson:"omega-6-fat_100g"`
		Omega6Fat                    float64 `json:"omega-6-fat" bson:"omega-6-fat"`
		LinoleicAcid100g             float64 `json:"linoleic-acid_100g" bson:"linoleic-acid_100g"`
		LinoleicAcid                 float64 `json:"linoleic-acid" bson:"linoleic-acid"`
		GammaLinolenicAcid100g       float64 `json:"gamma-linolenic-acid_100g" bson:"gamma-linolenic-acid_100g"`
		GammaLinolenicAcid           float64 `json:"gamma-linolenic-acid" bson:"gamma-linolenic-acid"`
		DihomoGammaLinolenicAcid100g float64 `json:"dihomo-gamma-linolenic-acid_100g" bson:"dihomo-gamma-linolenic-acid_100g"`
		DihomoGammaLinolenicAcid     float64 `json:"dihomo-gamma-linolenic-acid" bson:"dihomo-gamma-linolenic-acid"`
		Omega9Fat100g                float64 `json:"omega-9-fat_100g" bson:"omega-9-fat_100g"`
		Omega9Fat                    float64 `json:"omega-9-fat" bson:"omega-9-fat"`
		OleicAcid100g                float64 `json:"oleic-acid_100g" bson:"oleic-acid_100g"`
		OleicAcid                    float64 `json:"oleic-acid" bson:"oleic-acid"`
		ElaidicAcid100g              float64 `json:"elaidic-acid_100g" bson:"elaidic-acid_100g"`
		ElaidicAcid                  float64 `json:"elaidic-acid" bson:"elaidic-acid"`
		GondoicAcid100g              float64 `json:"gondoic-acid_100g" bson:"gondoic-acid_100g"`
		GondoicAcid                  float64 `json:"gondoic-acid" bson:"gondoic-acid"`
		MeadAcid100g                 float64 `json:"mead-acid_100g" bson:"mead-acid_100g"`
		MeadAcid                     float64 `json:"mead-acid" bson:"mead-acid"`
		ErucicAcid100g               float64 `json:"erucic-acid_100g" bson:"erucic-acid_100g"`
		ErucicAcid                   float64 `json:"erucic-acid" bson:"erucic-acid"`
		NervonicAcid100g             float64 `json:"nervonic-acid_100g" bson:"nervonic-acid_100g"`
		NervonicAcid                 float64 `json:"nervonic-acid" bson:"nervonic-acid"`
		TransFat100g                 float64 `json:"trans-fat_100g" bson:"trans-fat_100g"`
		TransFat                     float64 `json:"trans-fat" bson:"trans-fat"`
		Cholesterol100g              float64 `json:"cholesterol_100g" bson:"cholesterol_100g"`
		Cholesterol                  float64 `json:"cholesterol" bson:"cholesterol"`
		Fiber100g                    float64 `json:"fiber_100g" bson:"fiber_100g"`
		Fiber                        float64 `json:"fiber" bson:"fiber"`
		Sodium100g                   float64 `json:"sodium_100g" bson:"sodium_100g"`
		Sodium                       float64 `json:"sodium" bson:"sodium"`
		Alcohol100g                  float64 `json:"alcohol_100g" bson:"alcohol_100g"`
		Alcohol                      float64 `json:"alcohol" bson:"alcohol"`
		VitaminA100g                 float64 `json:"vitamin-a_100g" bson:"vitamin-a_100g"`
		VitaminA                     float64 `json:"vitamin-a" bson:"vitamin-a"`
		VitaminD100g                 float64 `json:"vitamin-d_100g" bson:"vitamin-d_100g"`
		VitaminD                     float64 `json:"vitamin-d" bson:"vitamin-d"`
		VitaminE100g                 float64 `json:"vitamin-e_100g" bson:"vitamin-e_100g"`
		VitaminE                     float64 `json:"vitamin-e" bson:"vitamin-e"`
		VitaminK100g                 float64 `json:"vitamin-k_100g" bson:"vitamin-k_100g"`
		VitaminK                     float64 `json:"vitamin-k" bson:"vitamin-k"`
		VitaminC100g                 float64 `json:"vitamin-c_100g" bson:"vitamin-c_100g"`
		VitaminC                     float64 `json:"vitamin-c" bson:"vitamin-c"`
		VitaminB1100g                float64 `json:"vitamin-b1_100g" bson:"vitamin-b1_100g"`
		VitaminB1                    float64 `json:"vitamin-b1" bson:"vitamin-b1"`
		VitaminB2100g                float64 `json:"vitamin-b2_100g" bson:"vitamin-b2_100g"`
		VitaminB2                    float64 `json:"vitamin-b2" bson:"vitamin-b2"`
		VitaminPp100g                float64 `json:"vitamin-pp_100g" bson:"vitamin-pp_100g"`
		VitaminPp                    float64 `json:"vitamin-pp" bson:"vitamin-pp"`
		VitaminB6100g                float64 `json:"vitamin-b6_100g" bson:"vitamin-b6_100g"`
		VitaminB6                    float64 `json:"vitamin-b6" bson:"vitamin-b6"`
		VitaminB9100g                float64 `json:"vitamin-b9_100g" bson:"vitamin-b9_100g"`
		VitaminB9                    float64 `json:"vitamin-b9" bson:"vitamin-b9"`
		VitaminB12100g               float64 `json:"vitamin-b12_100g" bson:"vitamin-b12_100g"`
		VitaminB12                   float64 `json:"vitamin-b12" bson:"vitamin-b12"`
		Biotin100g                   float64 `json:"biotin_100g" bson:"biotin_100g"`
		Biotin                       float64 `json:"biotin" bson:"biotin"`
		PantothenicAcid100g          float64 `json:"pantothenic-acid_100g" bson:"pantothenic-acid_100g"`
		PantothenicAcid              float64 `json:"pantothenic-acid" bson:"pantothenic-acid"`
		Silica100g                   float64 `json:"silica_100g" bson:"silica_100g"`
		Silica                       float64 `json:"silica" bson:"silica"`
		Bicarbonate100g              float64 `json:"bicarbonate_100g" bson:"bicarbonate_100g"`
		Bicarbonate                  float64 `json:"bicarbonate" bson:"bicarbonate"`
		Potassium100g                float64 `json:"potassium_100g" bson:"potassium_100g"`
		Potassium                    float64 `json:"potassium" bson:"potassium"`
		Chloride100g                 float64 `json:"chloride_100g" bson:"chloride_100g"`
		Chloride                     float64 `json:"chloride" bson:"chloride"`
		Calcium100g                  float64 `json:"calcium_100g" bson:"calcium_100g"`
		Calcium                      float64 `json:"calcium" bson:"calcium"`
		Phosphorus100g               float64 `json:"phosphorus_100g" bson:"phosphorus_100g"`
		Phosphorus                   float64 `json:"phosphorus" bson:"phosphorus"`
		Iron100g                     float64 `json:"iron_100g" bson:"iron_100g"`
		Iron                         float64 `json:"iron" bson:"iron"`
		Magnesium100g                float64 `json:"magnesium_100g" bson:"magnesium_100g"`
		Magnesium                    float64 `json:"magnesium" bson:"magnesium"`
		Zinc100g                     float64 `json:"zinc_100g" bson:"zinc_100g"`
		Zinc                         float64 `json:"zinc" bson:"zinc"`
		Copper100g                   float64 `json:"copper_100g" bson:"copper_100g"`
		Copper                       float64 `json:"copper" bson:"copper"`
		Manganese100g                float64 `json:"manganese_100g" bson:"manganese_100g"`
		Manganese                    float64 `json:"manganese" bson:"manganese"`
		Fluoride100g                 float64 `json:"fluoride_100g" bson:"fluoride_100g"`
		Fluoride                     float64 `json:"fluoride" bson:"fluoride"`
		Selenium100g                 float64 `json:"selenium_100g" bson:"selenium_100g"`
		Selenium                     float64 `json:"selenium" bson:"selenium"`
		Chromium100g                 float64 `json:"chromium_100g" bson:"chromium_100g"`
		Chromium                     float64 `json:"chromium" bson:"chromium"`
		Molybdenum100g               float64 `json:"molybdenum_100g" bson:"molybdenum_100g"`
		Molybdenum                   float64 `json:"molybdenum" bson:"molybdenum"`
		Iodine100g                   float64 `json:"iodine_100g" bson:"iodine_100g"`
		Iodine                       float64 `json:"iodine" bson:"iodine"`
		Caffeine100g                 float64 `json:"caffeine_100g" bson:"caffeine_100g"`
		Caffeine                     float64 `json:"caffeine" bson:"caffeine"`
		Taurine100g                  float64 `json:"taurine_100g" bson:"taurine_100g"`
		Taurine                      float64 `json:"taurine" bson:"taurine"`
		Ph100g                       float64 `json:"ph_100g" bson:"ph_100g"`
		Ph                           float64 `json:"ph" bson:"ph"`
		FruitsVegetablesNuts100g     float64 `json:"fruits-vegetables-nuts_100g" bson:"fruits-vegetables-nuts_100g"`
		FruitsVegetablesNuts         float64 `json:"fruits-vegetables-nuts" bson:"fruits-vegetables-nuts"`
		CarbonFootprint100g          float64 `json:"carbon-footprint_100g" bson:"carbon-footprint_100g"`
		CarbonFootprint              float64 `json:"carbon-footprint" bson:"carbon-footprint"`
		NutritionScoreFr100g         float64 `json:"nutrition-score-fr_100g" bson:"nutrition-score-fr_100g"`
		NutritionScoreFr             float64 `json:"nutrition-score-fr" bson:"nutrition-score-fr"`
		NutritionScoreUk100g         float64 `json:"nutrition-score-uk_100g" bson:"nutrition-score-uk_100g"`
		NutritionScoreUk             float64 `json:"nutrition-score-uk" bson:"nutrition-score-uk"`
	} `json:"nutriments_estimated" bson:"nutriments_estimated"`
}
