package product

type Product struct {
	ID_         string `json:"_id" bson:"_id"`
	Brands      string `json:"brands" bson:"brands"`
	ProductName string `json:"product_name" bson:"product_name"`
	Quantity    string `json:"quantity" bson:"quantity"`
	Nutriments  struct {
		SaturatedFat                                          float64 `json:"saturated-fat" bson:"saturated-fat,truncate"`
		SodiumValue                                           float64 `json:"sodium_value" bson:"sodium_value,truncate"`
		MonounsaturatedFatUnit                                string  `json:"monounsaturated-fat_unit" bson:"monounsaturated-fat_unit"`
		SaltValue                                             float64 `json:"salt_value" bson:"salt_value,truncate"`
		EnergyKcal100g                                        float64 `json:"energy-kcal_100g" bson:"energy-kcal_100g,truncate"`
		EnergyKcalValue                                       float64 `json:"energy-kcal_value" bson:"energy-kcal_value,truncate"`
		MonounsaturatedFat                                    float64 `json:"monounsaturated-fat" bson:"monounsaturated-fat,truncate"`
		FatValue                                              float64 `json:"fat_value" bson:"fat_value,truncate"`
		FruitsVegetablesLegumesEstimateFromIngredientsServing float64 `json:"fruits-vegetables-legumes-estimate-from-ingredients_serving" bson:"fruits-vegetables-legumes-estimate-from-ingredients_serving,truncate"`
		ProteinsValue                                         float64 `json:"proteins_value" bson:"proteins_value,truncate"`
		TransFatValue                                         float64 `json:"trans-fat_value" bson:"trans-fat_value,truncate"`
		FruitsVegetablesNutsEstimateFromIngredientsServing    float64 `json:"fruits-vegetables-nuts-estimate-from-ingredients_serving" bson:"fruits-vegetables-nuts-estimate-from-ingredients_serving,truncate"`
		EnergyServing                                         float64 `json:"energy_serving" bson:"energy_serving,truncate"`
		SaturatedFatValue                                     float64 `json:"saturated-fat_value" bson:"saturated-fat_value,truncate"`
		ProteinsUnit                                          string  `json:"proteins_unit" bson:"proteins_unit"`
		Salt                                                  float64 `json:"salt" bson:"salt,truncate"`
		Carbohydrates                                         float64 `json:"carbohydrates" bson:"carbohydrates,truncate"`
		Salt100g                                              float64 `json:"salt_100g" bson:"salt_100g,truncate"`
		NovaGroup                                             float64 `json:"nova-group" bson:"nova-group,truncate"`
		NutritionScoreFr                                      float64 `json:"nutrition-score-fr" bson:"nutrition-score-fr,truncate"`
		EnergyKcalValueComputed                               float64 `json:"energy-kcal_value_computed" bson:"energy-kcal_value_computed,truncate"`
		NutritionScoreFr100g                                  float64 `json:"nutrition-score-fr_100g" bson:"nutrition-score-fr_100g,truncate"`
		MonounsaturatedFat100g                                float64 `json:"monounsaturated-fat_100g" bson:"monounsaturated-fat_100g,truncate"`
		EnergyUnit                                            string  `json:"energy_unit" bson:"energy_unit"`
		Energy100g                                            float64 `json:"energy_100g" bson:"energy_100g,truncate"`
		PolyunsaturatedFatValue                               float64 `json:"polyunsaturated-fat_value" bson:"polyunsaturated-fat_value,truncate"`
		Fat100g                                               float64 `json:"fat_100g" bson:"fat_100g,truncate"`
		CarbohydratesValue                                    float64 `json:"carbohydrates_value" bson:"carbohydrates_value,truncate"`
		EnergyKcalUnit                                        string  `json:"energy-kcal_unit" bson:"energy-kcal_unit"`
		Sodium                                                float64 `json:"sodium" bson:"sodium,truncate"`
		FatUnit                                               string  `json:"fat_unit" bson:"fat_unit"`
		FruitsVegetablesNutsEstimateFromIngredients100g       float64 `json:"fruits-vegetables-nuts-estimate-from-ingredients_100g" bson:"fruits-vegetables-nuts-estimate-from-ingredients_100g,truncate"`
		FatServing                                            float64 `json:"fat_serving" bson:"fat_serving,truncate"`
		Fat                                                   float64 `json:"fat" bson:"fat,truncate"`
		MonounsaturatedFatServing                             float64 `json:"monounsaturated-fat_serving" bson:"monounsaturated-fat_serving,truncate"`
		Carbohydrates100g                                     float64 `json:"carbohydrates_100g" bson:"carbohydrates_100g,truncate"`
		SaturatedFatUnit                                      string  `json:"saturated-fat_unit" bson:"saturated-fat_unit"`
		EnergyKcalServing                                     float64 `json:"energy-kcal_serving" bson:"energy-kcal_serving,truncate"`
		ProteinsServing                                       float64 `json:"proteins_serving" bson:"proteins_serving,truncate"`
		PolyunsaturatedFat                                    float64 `json:"polyunsaturated-fat" bson:"polyunsaturated-fat,truncate"`
		TransFat                                              float64 `json:"trans-fat" bson:"trans-fat,truncate"`
		PolyunsaturatedFatUnit                                string  `json:"polyunsaturated-fat_unit" bson:"polyunsaturated-fat_unit"`
		Proteins100g                                          float64 `json:"proteins_100g" bson:"proteins_100g,truncate"`
		PolyunsaturatedFatServing                             float64 `json:"polyunsaturated-fat_serving" bson:"polyunsaturated-fat_serving,truncate"`
		CarbohydratesServing                                  float64 `json:"carbohydrates_serving" bson:"carbohydrates_serving,truncate"`
		SodiumUnit                                            string  `json:"sodium_unit" bson:"sodium_unit"`
		Proteins                                              float64 `json:"proteins" bson:"proteins,truncate"`
		SaltServing                                           float64 `json:"salt_serving" bson:"salt_serving,truncate"`
		Sodium100g                                            float64 `json:"sodium_100g" bson:"sodium_100g,truncate"`
		SaltUnit                                              string  `json:"salt_unit" bson:"salt_unit"`
		Energy                                                float64 `json:"energy" bson:"energy,truncate"`
		EnergyValue                                           float64 `json:"energy_value" bson:"energy_value,truncate"`
		SaturatedFat100g                                      float64 `json:"saturated-fat_100g" bson:"saturated-fat_100g,truncate"`
		CarbohydratesUnit                                     string  `json:"carbohydrates_unit" bson:"carbohydrates_unit"`
		TransFatUnit                                          string  `json:"trans-fat_unit" bson:"trans-fat_unit"`
		NovaGroup100g                                         float64 `json:"nova-group_100g" bson:"nova-group_100g,truncate"`
		TransFat100g                                          float64 `json:"trans-fat_100g" bson:"trans-fat_100g,truncate"`
		SaturatedFatServing                                   float64 `json:"saturated-fat_serving" bson:"saturated-fat_serving,truncate"`
		MonounsaturatedFatValue                               float64 `json:"monounsaturated-fat_value" bson:"monounsaturated-fat_value,truncate"`
		SodiumServing                                         float64 `json:"sodium_serving" bson:"sodium_serving,truncate"`
		FruitsVegetablesLegumesEstimateFromIngredients100g    float64 `json:"fruits-vegetables-legumes-estimate-from-ingredients_100g" bson:"fruits-vegetables-legumes-estimate-from-ingredients_100g,truncate"`
		NovaGroupServing                                      float64 `json:"nova-group_serving" bson:"nova-group_serving,truncate"`
		PolyunsaturatedFat100g                                float64 `json:"polyunsaturated-fat_100g" bson:"polyunsaturated-fat_100g,truncate"`
		TransFatServing                                       float64 `json:"trans-fat_serving" bson:"trans-fat_serving,truncate"`
		EnergyKcal                                            float64 `json:"energy-kcal" bson:"energy-kcal,truncate"`
	} `json:"nutriments" bson:"nutriments"`
	NutrimentsEstimated struct {
		BetaCarotene_100g    float64 `json:"beta-carotene_100g" bson:"beta-carotene_100g"`
		SaturatedFat_100g    float64 `json:"saturated-fat_100g" bson:"saturated-fat_100g"`
		VitaminB6_100g       float64 `json:"vitamin-b6_100g" bson:"vitamin-b6_100g"`
		VitaminB1_100g       float64 `json:"vitamin-b1_100g" bson:"vitamin-b1_100g"`
		VitaminE_100g        float64 `json:"vitamin-e_100g" bson:"vitamin-e_100g"`
		Maltose_100g         float64 `json:"maltose_100g" bson:"maltose_100g"`
		VitaminB12_100g      float64 `json:"vitamin-b12_100g" bson:"vitamin-b12_100g"`
		VitaminD_100g        float64 `json:"vitamin-d_100g" bson:"vitamin-d_100g"`
		Copper_100g          float64 `json:"copper_100g" bson:"copper_100g"`
		VitaminPP_100g       float64 `json:"vitamin-pp_100g" bson:"vitamin-pp_100g"`
		Salt_100g            float64 `json:"salt_100g" bson:"salt_100g"`
		Iron_100g            float64 `json:"iron_100g" bson:"iron_100g"`
		VitaminB2_100g       float64 `json:"vitamin-b2_100g" bson:"vitamin-b2_100g"`
		Lactose_100g         float64 `json:"lactose_100g" bson:"lactose_100g"`
		Cholesterol_100g     float64 `json:"cholesterol_100g" bson:"cholesterol_100g"`
		Iodine_100g          float64 `json:"iodine_100g" bson:"iodine_100g"`
		Potassium_100g       float64 `json:"potassium_100g" bson:"potassium_100g"`
		Fat_100g             float64 `json:"fat_100g" bson:"fat_100g"`
		EnergyKj_100g        float64 `json:"energy-kj_100g" bson:"energy-kj_100g"`
		Proteins_100g        float64 `json:"proteins_100g" bson:"proteins_100g"`
		Starch_100g          float64 `json:"starch_100g" bson:"starch_100g"`
		Water_100g           float64 `json:"water_100g" bson:"water_100g"`
		Energy_100g          float64 `json:"energy_100g" bson:"energy_100g"`
		EnergyKcal_100g      float64 `json:"energy-kcal_100g" bson:"energy-kcal_100g"`
		VitaminC_100g        float64 `json:"vitamin-c_100g" bson:"vitamin-c_100g"`
		Sodium_100g          float64 `json:"sodium_100g" bson:"sodium_100g"`
		Glucose_100g         float64 `json:"glucose_100g" bson:"glucose_100g"`
		Fructose_100g        float64 `json:"fructose_100g" bson:"fructose_100g"`
		Phylloquinone_100g   float64 `json:"phylloquinone_100g" bson:"phylloquinone_100g"`
		Galactose_100g       float64 `json:"galactose_100g" bson:"galactose_100g"`
		Selenium_100g        float64 `json:"selenium_100g" bson:"selenium_100g"`
		Zinc_100g            float64 `json:"zinc_100g" bson:"zinc_100g"`
		Magnesium_100g       float64 `json:"magnesium_100g" bson:"magnesium_100g"`
		VitaminA_100g        float64 `json:"vitamin-a_100g" bson:"vitamin-a_100g"`
		Sugars_100g          float64 `json:"sugars_100g" bson:"sugars_100g"`
		Phosphorus_100g      float64 `json:"phosphorus_100g" bson:"phosphorus_100g"`
		Manganese_100g       float64 `json:"manganese_100g" bson:"manganese_100g"`
		Sucrose_100g         float64 `json:"sucrose_100g" bson:"sucrose_100g"`
		Calcium_100g         float64 `json:"calcium_100g" bson:"calcium_100g"`
		Fiber_100g           float64 `json:"fiber_100g" bson:"fiber_100g"`
		Alcohol_100g         float64 `json:"alcohol_100g" bson:"alcohol_100g"`
		PantothenicAcid_100g float64 `json:"pantothenic-acid_100g" bson:"pantothenic-acid_100g"`
		Carbohydrates_100g   float64 `json:"carbohydrates_100g" bson:"carbohydrates_100g"`
		VitaminB9_100g       float64 `json:"vitamin-b9_100g" bson:"vitamin-b9_100g"`
		Polyols_100g         float64 `json:"polyols_100g" bson:"polyols_100g"`
	} `json:"nutriments_estimated" bson:"nutriments_estimated"`
}
