// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/products/search": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Search for products by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Search products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query (min 3 chars)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit results (default 10, max 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/product.Product"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get a single product by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get product by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/product.Product"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "product.Product": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string"
                },
                "brands": {
                    "type": "string"
                },
                "nutriments": {
                    "type": "object",
                    "properties": {
                        "carbohydrates": {
                            "type": "number"
                        },
                        "carbohydrates_100g": {
                            "type": "number"
                        },
                        "carbohydrates_serving": {
                            "type": "number"
                        },
                        "carbohydrates_unit": {
                            "type": "string"
                        },
                        "carbohydrates_value": {
                            "type": "number"
                        },
                        "energy": {
                            "type": "number"
                        },
                        "energy-kcal": {
                            "type": "number"
                        },
                        "energy-kcal_100g": {
                            "type": "number"
                        },
                        "energy-kcal_serving": {
                            "type": "number"
                        },
                        "energy-kcal_unit": {
                            "type": "string"
                        },
                        "energy-kcal_value": {
                            "type": "number"
                        },
                        "energy-kcal_value_computed": {
                            "type": "number"
                        },
                        "energy_100g": {
                            "type": "number"
                        },
                        "energy_serving": {
                            "type": "number"
                        },
                        "energy_unit": {
                            "type": "string"
                        },
                        "energy_value": {
                            "type": "number"
                        },
                        "fat": {
                            "type": "number"
                        },
                        "fat_100g": {
                            "type": "number"
                        },
                        "fat_serving": {
                            "type": "number"
                        },
                        "fat_unit": {
                            "type": "string"
                        },
                        "fat_value": {
                            "type": "number"
                        },
                        "fruits-vegetables-legumes-estimate-from-ingredients_100g": {
                            "type": "number"
                        },
                        "fruits-vegetables-legumes-estimate-from-ingredients_serving": {
                            "type": "number"
                        },
                        "fruits-vegetables-nuts-estimate-from-ingredients_100g": {
                            "type": "number"
                        },
                        "fruits-vegetables-nuts-estimate-from-ingredients_serving": {
                            "type": "number"
                        },
                        "monounsaturated-fat": {
                            "type": "number"
                        },
                        "monounsaturated-fat_100g": {
                            "type": "number"
                        },
                        "monounsaturated-fat_serving": {
                            "type": "number"
                        },
                        "monounsaturated-fat_unit": {
                            "type": "string"
                        },
                        "monounsaturated-fat_value": {
                            "type": "number"
                        },
                        "nova-group": {
                            "type": "number"
                        },
                        "nova-group_100g": {
                            "type": "number"
                        },
                        "nova-group_serving": {
                            "type": "number"
                        },
                        "nutrition-score-fr": {
                            "type": "number"
                        },
                        "nutrition-score-fr_100g": {
                            "type": "number"
                        },
                        "polyunsaturated-fat": {
                            "type": "number"
                        },
                        "polyunsaturated-fat_100g": {
                            "type": "number"
                        },
                        "polyunsaturated-fat_serving": {
                            "type": "number"
                        },
                        "polyunsaturated-fat_unit": {
                            "type": "string"
                        },
                        "polyunsaturated-fat_value": {
                            "type": "number"
                        },
                        "proteins": {
                            "type": "number"
                        },
                        "proteins_100g": {
                            "type": "number"
                        },
                        "proteins_serving": {
                            "type": "number"
                        },
                        "proteins_unit": {
                            "type": "string"
                        },
                        "proteins_value": {
                            "type": "number"
                        },
                        "salt": {
                            "type": "number"
                        },
                        "salt_100g": {
                            "type": "number"
                        },
                        "salt_serving": {
                            "type": "number"
                        },
                        "salt_unit": {
                            "type": "string"
                        },
                        "salt_value": {
                            "type": "number"
                        },
                        "saturated-fat": {
                            "type": "number"
                        },
                        "saturated-fat_100g": {
                            "type": "number"
                        },
                        "saturated-fat_serving": {
                            "type": "number"
                        },
                        "saturated-fat_unit": {
                            "type": "string"
                        },
                        "saturated-fat_value": {
                            "type": "number"
                        },
                        "sodium": {
                            "type": "number"
                        },
                        "sodium_100g": {
                            "type": "number"
                        },
                        "sodium_serving": {
                            "type": "number"
                        },
                        "sodium_unit": {
                            "type": "string"
                        },
                        "sodium_value": {
                            "type": "number"
                        },
                        "trans-fat": {
                            "type": "number"
                        },
                        "trans-fat_100g": {
                            "type": "number"
                        },
                        "trans-fat_serving": {
                            "type": "number"
                        },
                        "trans-fat_unit": {
                            "type": "string"
                        },
                        "trans-fat_value": {
                            "type": "number"
                        }
                    }
                },
                "nutriments_estimated": {
                    "type": "object",
                    "properties": {
                        "alcohol_100g": {
                            "type": "number"
                        },
                        "beta-carotene_100g": {
                            "type": "number"
                        },
                        "calcium_100g": {
                            "type": "number"
                        },
                        "carbohydrates_100g": {
                            "type": "number"
                        },
                        "cholesterol_100g": {
                            "type": "number"
                        },
                        "copper_100g": {
                            "type": "number"
                        },
                        "energy-kcal_100g": {
                            "type": "number"
                        },
                        "energy-kj_100g": {
                            "type": "number"
                        },
                        "energy_100g": {
                            "type": "number"
                        },
                        "fat_100g": {
                            "type": "number"
                        },
                        "fiber_100g": {
                            "type": "number"
                        },
                        "fructose_100g": {
                            "type": "number"
                        },
                        "galactose_100g": {
                            "type": "number"
                        },
                        "glucose_100g": {
                            "type": "number"
                        },
                        "iodine_100g": {
                            "type": "number"
                        },
                        "iron_100g": {
                            "type": "number"
                        },
                        "lactose_100g": {
                            "type": "number"
                        },
                        "magnesium_100g": {
                            "type": "number"
                        },
                        "maltose_100g": {
                            "type": "number"
                        },
                        "manganese_100g": {
                            "type": "number"
                        },
                        "pantothenic-acid_100g": {
                            "type": "number"
                        },
                        "phosphorus_100g": {
                            "type": "number"
                        },
                        "phylloquinone_100g": {
                            "type": "number"
                        },
                        "polyols_100g": {
                            "type": "number"
                        },
                        "potassium_100g": {
                            "type": "number"
                        },
                        "proteins_100g": {
                            "type": "number"
                        },
                        "salt_100g": {
                            "type": "number"
                        },
                        "saturated-fat_100g": {
                            "type": "number"
                        },
                        "selenium_100g": {
                            "type": "number"
                        },
                        "sodium_100g": {
                            "type": "number"
                        },
                        "starch_100g": {
                            "type": "number"
                        },
                        "sucrose_100g": {
                            "type": "number"
                        },
                        "sugars_100g": {
                            "type": "number"
                        },
                        "vitamin-a_100g": {
                            "type": "number"
                        },
                        "vitamin-b12_100g": {
                            "type": "number"
                        },
                        "vitamin-b1_100g": {
                            "type": "number"
                        },
                        "vitamin-b2_100g": {
                            "type": "number"
                        },
                        "vitamin-b6_100g": {
                            "type": "number"
                        },
                        "vitamin-b9_100g": {
                            "type": "number"
                        },
                        "vitamin-c_100g": {
                            "type": "number"
                        },
                        "vitamin-d_100g": {
                            "type": "number"
                        },
                        "vitamin-e_100g": {
                            "type": "number"
                        },
                        "vitamin-pp_100g": {
                            "type": "number"
                        },
                        "water_100g": {
                            "type": "number"
                        },
                        "zinc_100g": {
                            "type": "number"
                        }
                    }
                },
                "product_name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Database API Wrapper",
	Description:      "API for accessing the SnackLog product database.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
